blank_issues_enabled: false
contact_links:
  - name: Proceso de GitFlow
    url: https://github.com/MPorras01/ShopWithCoplitoTest/blob/master/docs/gitflow-process.md
    about: Revisa el flujo obligatorio de HU + PR + aprobacion.
